import type { PortfolioItem } from "./types";

// This would typically come from a database or API
const portfolioData: PortfolioItem[] = [
  {
    id: "1",
    title: "Celebrity",
    slug: "Celebrity",
    description: "Special edition photoshoot for Celebrity",
    imageUrl: "/celebrity/01.jpg",
    categories: ["fashion", "celebrity"],
    publication: "Celebrity",
    galleryImages: [
      { url: "/celebrity/01.jpg" },
      { url: "/celebrity/052A8646_After.jpg" },
      { url: "/celebrity/DSC03056_After.jpg" },
      { url: "/celebrity/DSC03071_After.jpg" },
      { url: "/celebrity/DSC03121_After.jpg" },
      { url: "/celebrity/DSC07914.jpg" },
    ],
  },
  {
    id: "2",
    title: "Couture",
    slug: "couture",
    description: "Fashion editorial featuring spotted pattern designs",
    imageUrl: "/couture/001.jpg",
    categories: ["fashion", "couture"],
    galleryImages: [
      { url: "/couture/DSC09996.jpg" },
      { url: "/couture/001.jpg" },
      { url: "/couture/DSC07747.jpg" },
      { url: "/couture/01_2.jpg" },
      { url: "/couture/011.jpg" },
      { url: "/couture/DSC_5502.jpg" },
      { url: "/couture/DSC_5616.jpg" },
      { url: "/couture/DSC04887_After.jpg" },
      { url: "/couture/14.jpg" },
      { url: "/couture/12.jpg" },
      { url: "/couture/DSC00102 copy.jpg" },
      { url: "/couture/03.jpg" },
      { url: "/couture/02 (2).jpg" },
      { url: "/couture/09.jpg" },
      { url: "/couture/11.jpg" },
      { url: "/couture/DSC08689_After.jpg" },
      { url: "/couture/13.jpg" },
      { url: "/couture/02.jpg" },
      { url: "/couture/DSC08788_After.jpg" },
      { url: "/couture/08.jpg" },
      { url: "/couture/DSC08981_After.jpg" },
      { url: "/couture/10.jpg" },
      { url: "/couture/07.jpg" },
      { url: "/couture/DSC08928_After.jpg" },
      { url: "/couture/05.jpg" },
      { url: "/couture/01.jpg" },
      { url: "/couture/DSC08858_After.jpg" },
    ],
  },
  {
    id: "3",
    title: "Fashion",
    slug: "fashion",
    description: "Elegant evening wear photoshoot",
    imageUrl: "/fashion/01.jpg",
    categories: ["fashion"],
    galleryImages: [
      { url: "/fashion/0015.jpg" },
      { url: "/fashion/0017.jpg" },
      { url: "/fashion/003.jpg" },
      { url: "/fashion/004 (2).jpg" },
      { url: "/fashion/004.jpg" },
      { url: "/fashion/005.jpg" },
      { url: "/fashion/006.jpg" },
      { url: "/fashion/008.jpg" },
      { url: "/fashion/01 (2).jpg" },
      { url: "/fashion/01.jpg" },
      { url: "/fashion/011.jpg" },
      { url: "/fashion/014.jpg" },
      { url: "/fashion/015.jpg" },
      { url: "/fashion/017.jpg" },
      { url: "/fashion/018.jpg" },
      { url: "/fashion/02.jpg" },
      { url: "/fashion/03.jpg" },
      { url: "/fashion/04.jpg" },
      { url: "/fashion/05.jpg" },
      { url: "/fashion/06.jpg" },
      { url: "/fashion/07.jpg" },
      { url: "/fashion/08.jpg" },
      { url: "/fashion/09.jpg" },
      { url: "/fashion/10.jpg" },
      { url: "/fashion/11.jpg" },
      { url: "/fashion/12.jpg" },
      { url: "/fashion/13.jpg" },
      { url: "/fashion/14.jpg" },
      { url: "/fashion/15.jpg" },
      { url: "/fashion/16.jpg" },
      { url: "/fashion/17.jpg" },
      { url: "/fashion/18.jpg" },
      { url: "/fashion/19.jpg" },
      { url: "/fashion/DSC00061.jpg" },
      { url: "/fashion/DSC00129.jpg" },
      { url: "/fashion/DSC00139.jpg" },
      { url: "/fashion/DSC00911_After.jpg" },
      { url: "/fashion/DSC01810_After.jpg" },
      { url: "/fashion/DSC09957.jpg" },
    ],
  },
  {
    id: "4",
    title: "Jewellery",
    slug: "jewellery",
    description: "Bright and vibrant summer collection",
    imageUrl: "/jewellery/01.jpg",
    categories: ["jewellery", "fashion"],
    galleryImages: [
      { url: "/jewellery/001.jpg" },
      { url: "/jewellery/003 (2).jpg" },
      { url: "/jewellery/003.jpg" },
      { url: "/jewellery/006.JPG" },
      { url: "/jewellery/01.jpg" },
      { url: "/jewellery/02.jpg" },
      { url: "/jewellery/03.jpg" },
      { url: "/jewellery/04.jpg" },
      { url: "/jewellery/06.jpg" },
      { url: "/jewellery/DSC00171.jpg" },
      { url: "/jewellery/DSC00194.jpg" },
      { url: "/jewellery/DSC01375_After.jpg" },
      { url: "/jewellery/DSC05731_After.jpg" },
      { url: "/jewellery/DSC05867_After.jpg" },
      { url: "/jewellery/DSC05995_After.jpg" },
      { url: "/jewellery/DSC06028_After.jpg" },
      { url: "/jewellery/DSC06039_After.jpg" },
      { url: "/jewellery/DSC06361_After.jpg" },
      { url: "/jewellery/DSC06551_After.jpg" },
      { url: "/jewellery/DSC06585_After.jpg" },
      { url: "/jewellery/DSC_6136.jpg" },
      { url: "/jewellery/DSC_6139 .jpg" },
      { url: "/jewellery/DSC_6205.jpg" },
      { url: "/jewellery/DSC_6546.jpg" },
    ],
  },
  {
    id: "5",
    title: "Skin Beauty",
    slug: "skin-beauty",
    description: "Natural beauty photoshoot highlighting skin care",
    imageUrl: "/skinbeauty/01.jpg",
    categories: ["beauty"],
    // publication: "BEAUTY INC",
    galleryImages: [
      { url: "/skinbeauty/01.jpg" },
      { url: "/skinbeauty/2.jpg" },
      { url: "/skinbeauty/3.jpg" },
      { url: "/skinbeauty/4.jpg" },
      { url: "/skinbeauty/5.jpg" },
      { url: "/skinbeauty/6.jpg" },
      { url: "/skinbeauty/7.jpg" },
      { url: "/skinbeauty/8.jpg" },
      { url: "/skinbeauty/9.jpg" },
    ],
  },
  {
    id: "6",
    title: "Weddings",
    slug: "weddings",
    description: "wedding feature photoshoot",
    imageUrl: "/weddings/DSC00196.JPG",
    categories: ["wedding"],
    galleryImages: [
     { url: "/Weddings/DSC00196.JPG" },
      { url: "/Weddings/DSC00942.JPG" },
      { url: "/Weddings/DSC01003.JPG" },
      { url: "/Weddings/DSC01018.JPG" },
      { url: "/Weddings/DSC01049.JPG" },
      { url: "/Weddings/DSC05542.JPG" },
      { url: "/Weddings/DSC05549.JPG" },
      { url: "/Weddings/DSC05844.JPG" },
      { url: "/Weddings/_SK_9102.JPG" },
      { url: "/Weddings/_SK_9132.JPG" },
    ],
  },
];

const HighLightData: PortfolioItem[] = [
  {
    id: "1",
    title: "Celebrity",
    slug: "Celebrity",
    description: "Special edition photoshoot for Celebrity",
    imageUrl: "/celebrity/01.jpg",
    categories: ["fashion", "celebrity"],
    publication: "Celebrity",
    galleryImages: [
      { url: "/celebrity/01.jpg" },
      { url: "/celebrity/052A8646_After.jpg" },
      { url: "/celebrity/DSC03056_After.jpg" },
      { url: "/celebrity/DSC03071_After.jpg" },
      { url: "/celebrity/DSC03121_After.jpg" },
      { url: "/celebrity/DSC07914.jpg" },
    ],
  },
  {
    id: "2",
    title: "Couture",
    slug: "Couture",
    description: "Fashion editorial featuring spotted pattern designs",
    imageUrl: "/couture/001.jpg",
    categories: ["fashion", "couture"],
    galleryImages: [
      { url: "/couture/DSC09996.jpg" },
      { url: "/couture/001.jpg" },
      { url: "/couture/DSC07747.jpg" },
      { url: "/couture/01_2.jpg" },
      { url: "/couture/011.jpg" },
      { url: "/couture/DSC_5502.jpg" },
      { url: "/couture/DSC_5616.jpg" },
      { url: "/couture/DSC04887_After.jpg" },
      { url: "/couture/14.jpg" },
      { url: "/couture/12.jpg" },
      { url: "/couture/DSC00102 copy.jpg" },
      { url: "/couture/03.jpg" },
      { url: "/couture/02 (2).jpg" },
      { url: "/couture/09.jpg" },
      { url: "/couture/11.jpg" },
      { url: "/couture/DSC08689_After.jpg" },
      { url: "/couture/13.jpg" },
      { url: "/couture/02.jpg" },
      { url: "/couture/DSC08788_After.jpg" },
      { url: "/couture/08.jpg" },
      { url: "/couture/DSC08981_After.jpg" },
      { url: "/couture/10.jpg" },
      { url: "/couture/07.jpg" },
      { url: "/couture/DSC08928_After.jpg" },
      { url: "/couture/05.jpg" },
      { url: "/couture/01.jpg" },
      { url: "/couture/DSC08858_After.jpg" },
    ],
  },
  {
    id: "3",
    title: "Fashion",
    slug: "fashion",
    description: "Elegant evening wear photoshoot",
    imageUrl: "/fashion/01.jpg",
    categories: ["fashion"],
    galleryImages: [
      { url: "/fashion/0015.jpg" },
      { url: "/fashion/0017.jpg" },
      { url: "/fashion/003.jpg" },
      { url: "/fashion/004 (2).jpg" },
      { url: "/fashion/004.jpg" },
      { url: "/fashion/005.jpg" },
      { url: "/fashion/006.jpg" },
      { url: "/fashion/008.jpg" },
      { url: "/fashion/01 (2).jpg" },
      { url: "/fashion/01.jpg" },
      { url: "/fashion/011.jpg" },
      { url: "/fashion/014.jpg" },
      { url: "/fashion/015.jpg" },
      { url: "/fashion/017.jpg" },
      { url: "/fashion/018.jpg" },
      { url: "/fashion/02.jpg" },
      { url: "/fashion/03.jpg" },
      { url: "/fashion/04.jpg" },
      { url: "/fashion/05.jpg" },
      { url: "/fashion/06.jpg" },
      { url: "/fashion/07.jpg" },
      { url: "/fashion/08.jpg" },
      { url: "/fashion/09.jpg" },
      { url: "/fashion/10.jpg" },
      { url: "/fashion/11.jpg" },
      { url: "/fashion/12.jpg" },
      { url: "/fashion/13.jpg" },
      { url: "/fashion/14.jpg" },
      { url: "/fashion/15.jpg" },
      { url: "/fashion/16.jpg" },
      { url: "/fashion/17.jpg" },
      { url: "/fashion/18.jpg" },
      { url: "/fashion/19.jpg" },
      { url: "/fashion/DSC00061.jpg" },
      { url: "/fashion/DSC00129.jpg" },
      { url: "/fashion/DSC00139.jpg" },
      { url: "/fashion/DSC00911_After.jpg" },
      { url: "/fashion/DSC01810_After.jpg" },
      { url: "/fashion/DSC09957.jpg" },
    ],
  },
];

export async function getPortfolioItems(): Promise<PortfolioItem[]> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 300));
  return portfolioData;
}

export async function getHightLightItems(): Promise<PortfolioItem[]> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 300));
  return HighLightData;
}

export async function getPortfolioItemBySlug(
  slug: string
): Promise<PortfolioItem | undefined> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 200));
  return portfolioData.find((item) => item.slug === slug);
}

export async function getRelatedPortfolioItems(
  currentId: string,
  category: string
): Promise<PortfolioItem[]> {
  // Simulate API delay
  await new Promise((resolve) => setTimeout(resolve, 200));

  return portfolioData
    .filter(
      (item) => item.id !== currentId && item.categories.includes(category)
    )
    .slice(0, 3);
}
